<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Partner</name>
   <tag></tag>
   <elementGuidId>bf1f6657-a600-4352-9a99-b31d9509be52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/nav/div/div/div/nav/a[5]/ul/div/div[2]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>54e283d3-1517-4522-a779-a523f2f9edaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-body2 MuiListItemText-primary css-eqyzcv-MuiTypography-root</value>
      <webElementGuid>6cd1c5ea-4de5-4a18-985b-8e0c9b212a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Partner</value>
      <webElementGuid>543c8131-0b5b-4607-bb57-e0d538545549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;page MuiBox-root css-k008qs&quot;]/nav[@class=&quot;MuiBox-root css-1mn6oro&quot;]/div[@class=&quot;MuiDrawer-root MuiDrawer-docked css-12de4fs-MuiDrawer-docked&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation0 MuiDrawer-paper MuiDrawer-paperAnchorLeft MuiDrawer-paperAnchorDockedLeft css-12i7wg6-MuiPaper-root-MuiDrawer-paper&quot;]/div[1]/nav[@class=&quot;MuiList-root MuiList-padding MuiList-dense sidebar css-h4y409-MuiList-root&quot;]/a[@class=&quot;MuiListItem-root MuiListItem-dense MuiListItem-gutters MuiListItem-padding css-n6de37-MuiListItem-root&quot;]/ul[@class=&quot;MuiList-root MuiList-padding css-1lbrbe2-MuiList-root&quot;]/div[@class=&quot;MuiButtonBase-root MuiListItemButton-root MuiListItemButton-dense MuiListItemButton-gutters MuiListItemButton-root MuiListItemButton-dense MuiListItemButton-gutters css-zf0mlb-MuiButtonBase-root-MuiListItemButton-root&quot;]/div[@class=&quot;MuiListItemText-root MuiListItemText-dense css-tlelie-MuiListItemText-root&quot;]/p[@class=&quot;MuiTypography-root MuiTypography-body2 MuiListItemText-primary css-eqyzcv-MuiTypography-root&quot;]</value>
      <webElementGuid>d13c490a-6025-4950-b32f-cb0435537d21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/nav/div/div/div/nav/a[5]/ul/div/div[2]/p</value>
      <webElementGuid>e97bc45c-7d80-4a21-b210-0193cd81bc34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hi, Welcome to GPM, mau ada projek apa hari ini?'])[1]/preceding::p[3]</value>
      <webElementGuid>cc04ac58-149d-43da-b725-7608bc5bdef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Project'])[1]/preceding::p[3]</value>
      <webElementGuid>bf887750-1ab7-48cd-b716-07f2fbdef0b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Partner']/parent::*</value>
      <webElementGuid>c1dfba5c-5734-419c-9fb8-a3ff3a6aa884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]/ul/div/div[2]/p</value>
      <webElementGuid>980ff563-c9c8-4b7c-b492-c37f276f9a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Partner' or . = 'Partner')]</value>
      <webElementGuid>01306902-4fdf-489b-932c-6ddafe3eba71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
